package com.alarmmanager.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.alarmmanager.model.entity.Users;
import com.alarmmanager.model.entity.Alarm;

import com.alarmmanager.model.dao.UsersDao;
import com.alarmmanager.model.dao.AlarmDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usersDaoConfig;
    private final DaoConfig alarmDaoConfig;

    private final UsersDao usersDao;
    private final AlarmDao alarmDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        alarmDaoConfig = daoConfigMap.get(AlarmDao.class).clone();
        alarmDaoConfig.initIdentityScope(type);

        usersDao = new UsersDao(usersDaoConfig, this);
        alarmDao = new AlarmDao(alarmDaoConfig, this);

        registerDao(Users.class, usersDao);
        registerDao(Alarm.class, alarmDao);
    }
    
    public void clear() {
        usersDaoConfig.clearIdentityScope();
        alarmDaoConfig.clearIdentityScope();
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

    public AlarmDao getAlarmDao() {
        return alarmDao;
    }

}
