package com.alarmmanager.model.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ALARM".
 */
@Entity
public class Alarm {

    @Id(autoincrement = true)
    private Long id;
    private String time;
    private String tone;

    @Generated(hash = 1972324134)
    public Alarm() {
    }

    public Alarm(Long id) {
        this.id = id;
    }

    @Generated(hash = 1209901238)
    public Alarm(Long id, String time, String tone) {
        this.id = id;
        this.time = time;
        this.tone = tone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getTone() {
        return tone;
    }

    public void setTone(String tone) {
        this.tone = tone;
    }

}
